### PR TITLE
added  icon class & changed Icons for uniformity 

### PR DESCRIPTION
**Pull request by version0chiro**
As the icons belonged to different collections it was causing the problem with them having equal size, I changed the icons to belong to the same collection and giving them a fix height and width using css classes gave it uniformity.

### CODE REVIEW

**Comment by version0chiro** [comment]
I have removed the navbar as requested.

**Comment by version0chiro** [comment]
Also Changed the video from iframe to a file video.

**Comment by UPstartDeveloper** [comment]
Wow, thanks for really stepping in to help out @version0chiro! Lmk if u ever need any help on your projects, I want to be able to repay this favor.

**Comment by version0chiro** [comment]
Was happy to help @UPstartDeveloper! 🎉🎉

**Pull request merged**
